esphome:
  name: esp32s3-dev
  platform: ESP32
  board: esp32-s3-devkitc-1

wifi:
  networks:
  - ssid: !secret wifi_ssid0
    password: !secret wifi_password0
  - ssid: !secret wifi_ssid1
    password: !secret wifi_password1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HKC3PyJFOmGUy+EjcGBwa4sedHLB7PUAWReQyLSPMIY="

# Example sensor (replace with your actual sensor if available)
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 1s
