substitutions:
  company_name: FutureProofHomes
  project_name: Satellite1

  #set this version by GHA at build time
  esp32_fw_version: dev

packages:
  home-assistant-voice: !include satellite1.base.yaml


esphome:
  project:
    name: ${company_name}.${project_name}
    version: ${esp32_fw_version}



http_request:

ota:
  - platform: http_request
    id: ota_http_request


external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ satellite1, memory_flasher, tas2780, pcm5122, fusb302b ]


logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: debug


