substitutions:
  node_name: satellite-va
  core_revision: "3"
  led_ring_id: "satellite1_led_ring"

packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml
  local: !include common/local_components.yaml
  sensors: !include common/hat_sensors_r3.yaml
  vk: !include common/nabu_vk_duplex_r3.yaml
  va: !include common/va.yaml
  led_ring: !include 
    file: common/led_ring.yaml
    vars:
      led_ring_platform: satellite1

esphome:
  project:
    name: satellite1.voice_assistant_r${core_revision}
    version: dev
  
  on_boot:
    priority: 375
    then:
      # Run the script to refresh the LED status
      - script.execute: update_leds
      - delay: 1s
      
      # If after 10 minutes, the device is still initializing (It did not yet connect to Home Assistant), turn off the init_in_progress variable and run the script to refresh the LED status
      - delay: 10min
      - if:
          condition:
            lambda: return id(init_in_progress);
          then:
            - lambda: id(init_in_progress) = false;
            - script.execute: update_leds

logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: DEBUG

api:
  id: api_id
  on_client_connected:
    - lambda: id(init_in_progress) = false;
    - script.execute: update_leds
  on_client_disconnected:
    - script.execute: update_leds

ota:
  - platform: satellite1
    id: ota_satellite1_xmos

http_request:

i2c:
  - id: bus_a
    sda: GPIO5
    scl: GPIO6
    frequency: 100kHz
    scan: True


spi:
  - id: spi_0
    clk_pin:  GPIO40
    mosi_pin: GPIO39
    miso_pin: GPIO41
    interface: SPI3


satellite1:
  spi_id: spi_0
  cs_pin: GPIO38
  data_rate: 1000
  spi_mode: MODE3
  xmos_rst_pin: GPIO12
  flash_sw_pin: GPIO14


binary_sensor:
  - platform: gpio
    id: btn_volume_up
    pin:
      satellite1: 
      port: INPUT_A
      pin: 0
      inverted: true
    name: "Volume Up"
  
  - platform: gpio
    id: btn_volume_down
    pin:
      satellite1: 
      port: INPUT_A
      pin: 2
      inverted: true
    name: "Volume Down"

  - platform: gpio
    id: btn_action
    pin:
      satellite1: 
      port: INPUT_A
      pin: 1
      inverted: true
    name: "Action"
  
  - platform: gpio
    id: inp_hw_mute
    pin:
      satellite1: 
      port: INPUT_A
      pin: 3
      inverted: false
    name: "Mics Muted"


light:
  - platform: satellite1
    id: !extend ${led_ring_id}
    name: LED-Ring
    

micro_wake_word:
  #model: github://esphome/micro-wake-word-models/models/v2/okay_nabu.json 
  models:
    - okay_nabu
  on_wake_word_detected:
    - lambda: id(voice_assistant_phase) = ${voice_assist_listening_phase_id};
    - script.execute: update_leds


button:
  - platform: template
    id: flash_satellite
    name: "Flash Satellite1"
    entity_category: diagnostic
    on_press:
      then:
        - ota.satellite1.flash:
            url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/v1.0.1-alpha.27/satellite1_firmware_adec.factory.bin
            md5_url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/v1.0.1-alpha.27/satellite1_firmware_adec.factory.md5


switch:
  - platform: template
    name: enable_mww
    id: sw_enable_mww
    optimistic: true
    restore_mode: ALWAYS_OFF
    
    on_turn_on:
      - micro_wake_word.start:
    
    on_turn_off:
    - micro_wake_word.stop: