substitutions:
  company_name: FutureProofHomes
  project_name: Satellite1

  #set this version by GHA at build time
  esp32_fw_version: dev

packages:
  # This is an inline package to prefix the on_client_connected with the wait_until action
  # It must appear before the actual package so it becomes the orignal config and the
  # on_client_connected list from the package config is appended onto this one.
  va_connected_wait_for_ble_and_flasher:
    voice_assistant:
      on_client_connected:
        - wait_until:
            not: ble.enabled
        - wait_until:
            not: memory_flasher.in_progress
        - delay: 2s
    wifi:
      on_disconnect:
        - ble.enable:
    
    satellite1:
      on_xmos_no_response:
        then:
          - if:
              condition:
                - lambda: return id(init_in_progress);
                - lambda: return id(xflash).flash_accessible();
                - lambda: return id(xflash).has_image_embedded();
              then:
                - logger.log: "shouldn't get here"
                - memory_flasher.write_embedded_image:
      
      on_xmos_connected:
        then:
          - delay: 1s
          - script.execute: control_leds

  home-assistant-voice: !include satellite1.yaml

esphome:
  project:
    name: ${company_name}.${project_name}
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    # source: https://firmware.esphome.io/home-assistant-voice-pe/home-assistant-voice/manifest.json
    source: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest.json

dashboard_import:
  # package_import_url: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
  package_import_url: github://FutureProofHomes/Satellite1-ESPHome/config/satellite1.yaml

wifi:
  enable_on_boot: true
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
    - script.execute: control_leds

improv_serial:

esp32_improv:
  authorizer: btn_action
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds

switch:
  - platform: template
    id: beta_firmware
    name: Beta firmware
    icon: "mdi:test-tube"
    entity_category: diagnostic
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Beta firmware"
      # - lambda: id(update_http_request).set_source_url("https://firmware.esphome.io/home-assistant-voice-pe/home-assistant-voice/manifest-beta.json");
      - lambda: id(update_http_request).set_source_url("https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest-beta.json");
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      # - lambda: id(update_http_request).set_source_url("https://firmware.esphome.io/home-assistant-voice-pe/home-assistant-voice/manifest.json");
      - lambda: id(update_http_request).set_source_url("https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest.json");