substitutions:
  node_name: "satellite-va"
  core_revision: "1"
  led_ring_id: "satellite1_led_ring"


packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml
  local: !include common/local_components.yaml
  sensors: !include common/hat_sensors.yaml
  vk: !include common/nabu_vk_duplex.yaml
  va: !include common/va.yaml
  versioning: !include common/versioning.yaml
  led_ring: !include 
    file: common/led_ring.yaml
    vars:
      led_ring_platform: satellite1
  

esphome:
  project:
    name: satellite1.voice_assistant_r${core_revision}
    version: dev


logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: DEBUG

api:
  id: api_id
  on_client_connected:
    - lambda: id(init_in_progress) = false;
    - script.execute: update_leds
  on_client_disconnected:
    - script.execute: update_leds


i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO18
    frequency: 100kHz
    scan: True

spi:
  - id: spi_0
    clk_pin:  GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13

ota:
  - platform: satellite1
    id: ota_satellite1_xmos

http_request:

satellite1:
  spi_id: spi_0
  cs_pin: GPIO10
  data_rate: 1000
  spi_mode: MODE3
  xmos_rst_pin: GPIO9 # not used in this revision
  flash_sw_pin: GPIO5 # not used in this revision

binary_sensor:
  - platform: gpio
    id: btn_volume_up
    pin:
      satellite1: 
      port: INPUT_A
      pin: 0
      inverted: true
    name: "Volume Up"
  
  - platform: gpio
    id: btn_volume_down
    pin:
      satellite1: 
      port: INPUT_A
      pin: 1
      inverted: true
    name: "Volume Down"


light:
  - platform: satellite1
    id: !extend ${led_ring_id}
    name: LED-Ring
    

micro_wake_word:
  #model: github://esphome/micro-wake-word-models/models/v2/okay_nabu.json 
  models:
    - okay_nabu
  on_wake_word_detected:
    - lambda: id(voice_assistant_phase) = ${voice_assist_listening_phase_id};
    - script.execute: update_leds
