substitutions:
  #Change to any preferred name
  friendly_name: "Satellite1"  

  #Recommend leaving the following unchanged
  node_name: satellite1
  company_name: FutureProofHomes
  project_name: Satellite1
  component_name: Core
  fw_version: "v2.0.0-alpha.8"
  built_with_core_hw_version: "v1.0.0-beta.1"
  built_with_hat_hw_version: "v1.0.0-beta.1"

esphome:
  name: ${node_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2024.2.0
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216

  project:
    name: ${company_name}.${project_name}
    version: ${fw_version}
  
  on_boot:
    - priority: 375
      then:
        # Run the script to refresh the LED status
        - script.execute: control_leds
        - delay: 1s
        
        # If after 10 minutes, the device is still initializing (It did not yet connect to Home Assistant), turn off the init_in_progress variable and run the script to refresh the LED status
        - delay: 10min
        - if:
            condition:
              lambda: return id(init_in_progress);
            then:
              - lambda: id(init_in_progress) = false;
              - script.execute: control_leds
    - priority: 600
      then:
        - logger.log: "${company_name} ${project_name} ${component_name} version ${built_with_core_hw_version} running firmware ${fw_version}"
        - delay: 30s
        - if:
            condition:
              lambda: return id(init_in_progress);
            then:
              - lambda: id(init_in_progress) = false;
    


esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
      CONFIG_ESP32_S3_BOX_BOARD: "y"


psram:
  mode: octal
  speed: 80MHz


ota:
  - platform: satellite1
    id: ota_satellite1_xmos


logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: DEBUG


status_led:
  pin: GPIO45


api:
  id: api_id
  on_client_connected:
    - lambda: id(init_in_progress) = false;
    - script.execute: control_leds
  on_client_disconnected:
    - script.execute: control_leds


http_request:

i2c:
  - id: bus_a
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: True


spi:
  - id: spi_0
    clk_pin:  GPIO40
    mosi_pin: GPIO39
    miso_pin: GPIO41
    interface: SPI3


satellite1:
  spi_id: spi_0
  cs_pin: GPIO38
  data_rate: 4000000
  spi_mode: MODE3
  xmos_rst_pin: GPIO12
  flash_sw_pin: GPIO14


packages:
  wifi: !include common/wifi_improv.yaml
  buttons: !include common/buttons.yaml
  media_player: !include common/media_player_r4.yaml
  voice_assistant: !include common/voice_assistant_r4.yaml
  led_ring: !include common/led_ring_r4.yaml
  hat_sensors: !include common/hat_sensors_r3.yaml
  timer: !include common/timer_r4.yaml
  debug: !include common/debug.yaml
  # versioning: !include common/versioning.yaml
  #TODO: Currently BLE tracker will cause device to intermittently crash (especially when streaming music)
  # ble_tracker: !include common/ble_tracker_r4.yaml 