substitutions:
  node_name: plain-core-board
  core_revision: "1"

packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml
  local: !include common/local_components.yaml

logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: VERBOSE

api:

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ satellite1 ]

spi:
  - id: spi_0
    clk_pin:  GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13
  
  - id: spi_1
    interface: spi3
    clk_pin:  GPIO16
    mosi_pin: GPIO5
    miso_pin: GPIO1


#ota:
#  - platform: satellite1
#    id: ota_satellite1_xmos
#    spi_id: spi_0
#    cs_pin: GPIO10
#http_request:


satellite1:
  spi_id: spi_0
  cs_pin: GPIO10
  data_rate: 4000000
  spi_mode: MODE3


switch:
  - platform: gpio
    id: expl_led_0
    name: "Explorer LED 1"
    pin:
      satellite1: 
      port: OUTPUT_A
      pin: 0

  - platform: gpio
    id: expl_led_1
    name: "Explorer LED 2"
    pin:
      satellite1: 
      port: OUTPUT_A
      pin: 1
  
  - platform: gpio
    id: expl_led_2
    name: "Explorer LED 3"
    pin:
      satellite1: 
      port: OUTPUT_A
      pin: 2

  - platform: gpio
    id: expl_led_3
    name: "Explorer LED 4"
    pin:
      satellite1: 
      port: OUTPUT_A
      pin: 3


binary_sensor:
  - platform: gpio
    pin:
      satellite1: 
      port: INPUT_A
      pin: 0
      inverted: true
    name: "Action Button 1"
  
  - platform: gpio
    pin:
      satellite1: 
      port: INPUT_A
      pin: 1
      inverted: true
    name: "Action Button 2"


light:
  - platform: satellite1
    name: LED-Ring
    id: led_ring
