substitutions:
  node_name: plain-core-board
  core_revision: "1"

packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml
  local: !include common/local_components.yaml
  dummy: !include common/dummy.yaml

logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: VERBOSE

api:

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ satellite1 ]

spi:
  - id: spi_0
    clk_pin:  GPIO40
    mosi_pin: GPIO39
    miso_pin: GPIO41
    interface: SPI3
  


ota:
  - platform: satellite1
    id: ota_satellite1_xmos

http_request:


satellite1:
  spi_id: spi_0
  cs_pin: GPIO38
  data_rate: 1000
  spi_mode: MODE3
  xmos_rst_pin: GPIO12
  flash_sw_pin: GPIO14


button:
  - platform: template
    id: flash_satellite
    name: "Flash Satellite1"
    entity_category: diagnostic
    on_press:
      then:
        - ota.satellite1.flash:
            url: https://github.com/FutureProofHomes/Documentation/blob/main/assets/firmware/xmos/v1.0.1-alpha.20/satellite1_firmware_adec.factory.bin?raw=true
            md5_url: https://github.com/FutureProofHomes/Documentation/blob/main/assets/firmware/xmos/v1.0.1-alpha.20/satellite1_firmware_adec.factory.md5?raw=true


