substitutions:
  node_name: plain-core-board

packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml

logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: VERBOSE

api:

