substitutions:
  node_name: plain-core-board
  core_revision: "1"

packages:
  device_base: !include common/board.yaml
  wifi: !include common/wifi_improv.yaml
  local: !include common/local_components.yaml
  dummy: !include common/dummy.yaml

logger:
  deassert_rts_dtr: true
  hardware_uart : USB_SERIAL_JTAG
  level: VERBOSE

api:

external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ satellite1 ]

spi:
  - id: spi_0
    clk_pin:  GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13
  


ota:
  - platform: satellite1
    id: ota_satellite1_xmos

http_request:


satellite1:
  spi_id: spi_0
  cs_pin: GPIO10
  data_rate: 1000
  spi_mode: MODE3
  xmos_rst_pin: GPIO9
  flash_sw_pin: GPIO5


button:
  - platform: template
    id: flash_satellite
    name: "Flash Satellite1"
    entity_category: diagnostic
    on_press:
      then:
        - ota.satellite1.flash:
            url: http://192.168.178.20:8080/satellite_firmware_bypass.bin
            md5_url: http://192.168.178.20:8080/satellite_firmware_bypass.bin.md5


