external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: allow_external_clk_mode
    components: [ adf_pipeline, i2s_audio ]


i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO11
    i2s_bclk_pin: GPIO5
    i2s_mclk_pin: GPIO3
    access_mode: duplex

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_clock_mode: external
    i2s_dout_pin: GPIO7
    adf_alc: true
    alc_max: .5
    channel: right_left
    sample_rate: 48000
    bits_per_sample: 32bit
    fixed_settings: true

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_shared
    i2s_clock_mode: external
    i2s_din_pin: GPIO6
    pdm: false
    channel: right_left
    sample_rate: 48000
    bits_per_sample: 32bit
    fixed_settings: true

