external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: allow_external_clk_mode
    components: [ adf_pipeline ]
  
  - source:
      type: local
      path: ../esphome/components
    components: [ i2s_audio ]


i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO02
    access_mode: duplex

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_clock_mode: internal
    i2s_dout_pin: GPIO16
    dac:
      model: pcm5122
      address: 0x4D
    adf_alc: false
    alc_max: .5
    channel: right_left
    sample_rate: 48000
    bits_per_sample: 32bit
    fixed_settings: true
