#Creates a global hub so that you can track bluetooth low energy devices using your ESP32 node: https://esphome.io/components/esp32_ble_tracker
#We we specify which device to track by using Bermuda in Home Assistant: https://github.com/agittins/bermuda 
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

switch:
  - platform: template
    name: Enable BLE Tracking
    id: sw_enable_bletracker
    optimistic: true
    restore_mode: ALWAYS_OFF
    
    on_turn_on:
      - esp32_ble_tracker.start_scan:
    
    on_turn_off:
      - esp32_ble_tracker.stop_scan: