button:
  # Restarts Sat1 Device
  - platform: restart
    name: "Restart Sat1"
    entity_category: diagnostic

  # Restarts Sat1 to safe mode
  - platform: safe_mode
    name: "Restart Sat1 (Safe Mode)"
    entity_category: diagnostic

  # Flashes Satellite1 with most recent XMOS firmware
  #TODO: This needs to grab the latest firmware and not hardcoded version
  - platform: template
    id: flash_satellite
    name: "Flash Latest XMOS FW"
    entity_category: diagnostic
    on_press:
      then:
        - ota.satellite1.flash:
            url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/v1.0.1-alpha.27/satellite1_firmware_adec.factory.bin
            md5_url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/v1.0.1-alpha.27/satellite1_firmware_adec.factory.md5

  # Restors the Sat1 ESP back to factory settings
  #TODO: What buttons do we want to long press to initiate this
  #TODO: Create the factory reset firmware
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset ESP32 FW"
    entity_category: diagnostic
    internal: true

binary_sensor:
  - platform: gpio
    id: btn_up
    pin:
      satellite1: 
      port: INPUT_A
      pin: 0
      inverted: true
    name: "Button Up (Vol+)"
    icon: "mdi:volume-plus"
    on_press:
      then:
        - lambda: id(volume_buttons_touched) = true;
        - script.execute:
            id: control_volume
            increase_volume: true
  
  - platform: gpio
    id: btn_down
    pin:
      satellite1: 
      port: INPUT_A
      pin: 2
      inverted: true
    name: "Button Down (Vol-)"
    icon: "mdi:volume-minus"
    on_press:
      then:
        - lambda: id(volume_buttons_touched) = true;
        - script.execute:
            id: control_volume
            increase_volume: false

  - platform: gpio
    id: btn_action
    pin:
      satellite1: 
      port: INPUT_A
      pin: 1
      inverted: true
    name: "Button Right (Action)"
    icon: "mdi:gesture-tap"
  
  - platform: gpio
    id: btn_left
    pin:
      satellite1: 
      port: INPUT_A
      pin: 3
      inverted: false
    name: "Button Left (HW Mute)"
    icon: "mdi:microphone-off"
    on_state:
      - if:
          condition:
            binary_sensor.is_off: btn_left
          then:
            - switch.template.publish:
                id: master_mute_switch
                state: OFF
          else:
            - switch.template.publish:
                id: master_mute_switch
                state: ON

