esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216
      
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 120MHz

i2c:
  - id: i2c_0
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: True

spi:
  - id: spi_0
    clk_pin:  GPIO40
    mosi_pin: GPIO39
    miso_pin: GPIO41
    interface: SPI3


