debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      entity_category: "diagnostic"
    reset_reason:
      name: "Reset Reason"
      entity_category: "diagnostic"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      entity_category: "diagnostic"
    block:
      name: "Heap Max Block"
      entity_category: "diagnostic"
    loop_time:
      name: "Loop Time"
      entity_category: "diagnostic"
    psram:
      name: "Free PSRAM"
      entity_category: "diagnostic"
  - platform: wifi_signal
    name: "Wi-Fi Signal Strength"
    entity_category: "diagnostic"
    update_interval: 60s