
external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ version ]

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      entity_category: "diagnostic"
    reset_reason:
      name: "Reset Reason"
      entity_category: "diagnostic"

  - platform: template
    name: "Compat. w/ CORE hw"
    entity_category: "diagnostic"
    icon: "mdi:chip"
    lambda: |-
      return std::string("${built_for_core_hw_version}");

  - platform: template
    name: "Compat. w/ HAT hw"
    entity_category: "diagnostic"
    icon: "mdi:chip"
    lambda: |-
      return std::string("${built_for_hat_hw_version}");

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      entity_category: "diagnostic"
    block:
      name: "Heap Max Block"
      entity_category: "diagnostic"
    loop_time:
      name: "Loop Time"
      entity_category: "diagnostic"
    psram:
      name: "Free PSRAM"
      entity_category: "diagnostic"
  - platform: wifi_signal
    name: "Wi-Fi Signal Strength"
    entity_category: "diagnostic"
    update_interval: 60s

button:
  # Restarts Sat1 to safe mode
  - platform: safe_mode
    name: "Restart Sat1 (Safe Mode)"
    entity_category: diagnostic

  # Flashes Sat1 HAT with specific XMOS firmware
  - platform: template
    id: flash_satellite
    name: "XMOS Flash ${xmos_fw_version}"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.write_image:
            image_version: ${xmos_fw_version}
            image_file: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/${xmos_fw_version}/satellite1_firmware_fixed_delay.factory.bin
            md5_url: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/assets/firmware/xmos/${xmos_fw_version}/satellite1_firmware_fixed_delay.factory.md5

  # Flashes Sat1 HAT with XMOS firmware embedded in the ESP32
  - platform: template
    id: flash_embedded
    name: "XMOS Flash Embedded FW"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.write_embedded_image:

  # Wipes the Satellite1 HAT XMOS Chip
  - platform: template
    id: erase_xmos_flash
    name: "XMOS Erase Chip"
    entity_category: diagnostic
    on_press:
      then:
        - memory_flasher.erase: