script:
# play testset flac files
  - id: play_subset_0
    then:

      - logger.log: "Playing: 01 - blocksize 4096.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/01%20-%20blocksize%204096.flac'
      - delay: 5s

      - logger.log: "Playing: 02 - blocksize 4608.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/02%20-%20blocksize%204608.flac'
      - delay: 5s

      - logger.log: "Playing: 03 - blocksize 16.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/03%20-%20blocksize%2016.flac'
      - delay: 5s

      - logger.log: "Playing: 04 - blocksize 192.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/04%20-%20blocksize%20192.flac'
      - delay: 5s

      - logger.log: "Playing: 05 - blocksize 254.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/05%20-%20blocksize%20254.flac'
      - delay: 5s

      - logger.log: "Playing: 06 - blocksize 512.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/06%20-%20blocksize%20512.flac'
      - delay: 5s

      - logger.log: "Playing: 07 - blocksize 725.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/07%20-%20blocksize%20725.flac'
      - delay: 5s

      - logger.log: "Playing: 08 - blocksize 1000.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/08%20-%20blocksize%201000.flac'
      - delay: 5s

      - logger.log: "Playing: 09 - blocksize 1937.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/09%20-%20blocksize%201937.flac'
      - delay: 5s

      - logger.log: "Playing: 10 - blocksize 2304.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/10%20-%20blocksize%202304.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_1
    then:

      - logger.log: "Playing: 11 - partition order 8.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/11%20-%20partition%20order%208.flac'
      - delay: 5s

      - logger.log: "Playing: 12 - qlp precision 15 bit.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/12%20-%20qlp%20precision%2015%20bit.flac'
      - delay: 5s

      - logger.log: "Playing: 13 - qlp precision 2 bit.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/13%20-%20qlp%20precision%202%20bit.flac'
      - delay: 5s

      - logger.log: "Playing: 14 - wasted bits.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/14%20-%20wasted%20bits.flac'
      - delay: 5s

      - logger.log: "Playing: 15 - only verbatim subframes.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/15%20-%20only%20verbatim%20subframes.flac'
      - delay: 5s

      - logger.log: "Playing: 16 - partition order 8 containing escaped partitions.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/16%20-%20partition%20order%208%20containing%20escaped%20partitions.flac'
      - delay: 5s

      - logger.log: "Playing: 17 - all fixed orders.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/17%20-%20all%20fixed%20orders.flac'
      - delay: 5s

      - logger.log: "Playing: 18 - precision search.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/18%20-%20precision%20search.flac'
      - delay: 5s

      - logger.log: "Playing: 19 - samplerate 35467Hz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/19%20-%20samplerate%2035467Hz.flac'
      - delay: 5s

      - logger.log: "Playing: 20 - samplerate 39kHz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/20%20-%20samplerate%2039kHz.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_2
    then:

      - logger.log: "Playing: 21 - samplerate 22050Hz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/21%20-%20samplerate%2022050Hz.flac'
      - delay: 5s

     #- logger.log: "Playing: 22 - 12 bit per sample.flac"
     # - wait_until:
     #     media_player.is_idle:
     # - media_player.play_media: 'http://192.168.178.20:8080/subset/22%20-%2012%20bit%20per%20sample.flac'
     # - delay: 5s

     # - logger.log: "Playing: 23 - 8 bit per sample.flac"
     # - wait_until:
     #     media_player.is_idle:
     # - media_player.play_media: 'http://192.168.178.20:8080/subset/23%20-%208%20bit%20per%20sample.flac'
     # - delay: 5s

      - logger.log: "Playing: 24 - variable blocksize file created with flake revision 264.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/24%20-%20variable%20blocksize%20file%20created%20with%20flake%20revision%20264.flac'
      - delay: 5s

      - logger.log: "Playing: 25 - variable blocksize file created with flake revision 264, modified to create smaller blocks.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/25%20-%20variable%20blocksize%20file%20created%20with%20flake%20revision%20264%2C%20modified%20to%20create%20smaller%20blocks.flac'
      - delay: 5s

      - logger.log: "Playing: 26 - variable blocksize file created with CUETools.Flake 2.1.6.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/26%20-%20variable%20blocksize%20file%20created%20with%20CUETools.Flake%202.1.6.flac'
      - delay: 5s


      - logger.log: "Playing: 27 - old format variable blocksize file created with Flake 0.11.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/27%20-%20old%20format%20variable%20blocksize%20file%20created%20with%20Flake%200.11.flac'
      - delay: 5s

      - logger.log: "Playing: 28 - high resolution audio, default settings.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/28%20-%20high%20resolution%20audio%2C%20default%20settings.flac'
      - delay: 5s

      - logger.log: "Playing: 29 - high resolution audio, blocksize 16384.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/29%20-%20high%20resolution%20audio%2C%20blocksize%2016384.flac'
      - delay: 5s

      - logger.log: "Playing: 30 - high resolution audio, blocksize 13456.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/30%20-%20high%20resolution%20audio%2C%20blocksize%2013456.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_3
    then:

      - logger.log: "Playing: 31 - high resolution audio, using only 32nd order predictors.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/31%20-%20high%20resolution%20audio%2C%20using%20only%2032nd%20order%20predictors.flac'
      - delay: 5s

      - logger.log: "Playing: 32 - high resolution audio, partition order 8 containing escaped partitions.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/32%20-%20high%20resolution%20audio%2C%20partition%20order%208%20containing%20escaped%20partitions.flac'
      - delay: 5s

      - logger.log: "Playing: 33 - samplerate 192kHz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/33%20-%20samplerate%20192kHz.flac'
      - delay: 5s

      - logger.log: "Playing: 34 - samplerate 192kHz, using only 32nd order predictors.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/34%20-%20samplerate%20192kHz%2C%20using%20only%2032nd%20order%20predictors.flac'
      - delay: 5s

      - logger.log: "Playing: 35 - samplerate 134560Hz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/35%20-%20samplerate%20134560Hz.flac'
      - delay: 5s

      - logger.log: "Playing: 36 - samplerate 384kHz.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/36%20-%20samplerate%20384kHz.flac'
      - delay: 5s

      - logger.log: "Playing: 37 - 20 bit per sample.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/37%20-%2020%20bit%20per%20sample.flac'
      - delay: 5s

      - logger.log: "Playing: 38 - 3 channels (3.0).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/38%20-%203%20channels%20%283.0%29.flac'
      - delay: 5s

      - logger.log: "Playing: 39 - 4 channels (4.0).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/39%20-%204%20channels%20%284.0%29.flac'
      - delay: 5s

      - logger.log: "Playing: 40 - 5 channels (5.0).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/40%20-%205%20channels%20%285.0%29.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_4
    then:

      - logger.log: "Playing: 41 - 6 channels (5.1).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/41%20-%206%20channels%20%285.1%29.flac'
      - delay: 5s

      - logger.log: "Playing: 42 - 7 channels (6.1).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/42%20-%207%20channels%20%286.1%29.flac'
      - delay: 5s

      - logger.log: "Playing: 43 - 8 channels (7.1).flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/43%20-%208%20channels%20%287.1%29.flac'
      - delay: 5s

      - logger.log: "Playing: 44 - 8-channel surround, 192kHz, 24 bit, using only 32nd order predictors.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/44%20-%208-channel%20surround%2C%20192kHz%2C%2024%20bit%2C%20using%20only%2032nd%20order%20predictors.flac'
      - delay: 5s

      - logger.log: "Playing: 45 - no total number of samples set.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/45%20-%20no%20total%20number%20of%20samples%20set.flac'
      - delay: 5s

      - logger.log: "Playing: 46 - no min-max framesize set.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/46%20-%20no%20min-max%20framesize%20set.flac'
      - delay: 5s

      - logger.log: "Playing: 47 - only STREAMINFO.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/47%20-%20only%20STREAMINFO.flac'
      - delay: 5s

      - logger.log: "Playing: 48 - Extremely large SEEKTABLE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/48%20-%20Extremely%20large%20SEEKTABLE.flac'
      - delay: 5s
      
      # TODO make sure to not get stuck when buffer size is to small to hold whole header incl large padding  
      - logger.log: "Playing: 49 - Extremely large PADDING.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/49%20-%20Extremely%20large%20PADDING.flac'
      - delay: 5s

      - logger.log: "Playing: 50 - Extremely large PICTURE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/50%20-%20Extremely%20large%20PICTURE.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_5
    then:

      - logger.log: "Playing: 51 - Extremely large VORBISCOMMENT.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/51%20-%20Extremely%20large%20VORBISCOMMENT.flac'
      - delay: 5s

      - logger.log: "Playing: 52 - Extremely large APPLICATION.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/52%20-%20Extremely%20large%20APPLICATION.flac'
      - delay: 5s

      - logger.log: "Playing: 53 - CUESHEET with very many indexes.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/53%20-%20CUESHEET%20with%20very%20many%20indexes.flac'
      - delay: 5s

      - logger.log: "Playing: 54 - 1000x repeating VORBISCOMMENT.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/54%20-%201000x%20repeating%20VORBISCOMMENT.flac'
      - delay: 5s

      - logger.log: "Playing: 55 - file 48-53 combined.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/55%20-%20file%2048-53%20combined.flac'
      - delay: 5s

      - logger.log: "Playing: 56 - JPG PICTURE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/56%20-%20JPG%20PICTURE.flac'
      - delay: 5s

      - logger.log: "Playing: 57 - PNG PICTURE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/57%20-%20PNG%20PICTURE.flac'
      - delay: 5s

      - logger.log: "Playing: 58 - GIF PICTURE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/58%20-%20GIF%20PICTURE.flac'
      - delay: 5s

      - logger.log: "Playing: 59 - AVIF PICTURE.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/59%20-%20AVIF%20PICTURE.flac'
      - delay: 5s

      - logger.log: "Playing: 60 - mono audio.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/60%20-%20mono%20audio.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset_6
    then:

      - logger.log: "Playing: 61 - predictor overflow check, 16-bit.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/61%20-%20predictor%20overflow%20check%2C%2016-bit.flac'
      - delay: 5s

      - logger.log: "Playing: 62 - predictor overflow check, 20-bit.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/62%20-%20predictor%20overflow%20check%2C%2020-bit.flac'
      - delay: 5s

      - logger.log: "Playing: 63 - predictor overflow check, 24-bit.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/63%20-%20predictor%20overflow%20check%2C%2024-bit.flac'
      - delay: 5s

      - logger.log: "Playing: 64 - rice partitions with escape code zero.flac"
      - wait_until:
          media_player.is_idle:
      - media_player.play_media: 'http://192.168.178.20:8080/subset/64%20-%20rice%20partitions%20with%20escape%20code%20zero.flac'
      - delay: 5s

# play testset flac files
  - id: play_subset
    then:
      - script.execute: play_subset_0
      - script.wait: play_subset_0
      - script.execute: play_subset_1
      - script.wait: play_subset_1
      - script.execute: play_subset_2
      - script.wait: play_subset_2
      - script.execute: play_subset_3
      - script.wait: play_subset_3
      - script.execute: play_subset_4
      - script.wait: play_subset_4
      - script.execute: play_subset_5
      - script.wait: play_subset_5
      - script.execute: play_subset_6
      - script.wait: play_subset_6
