sensor:
  # - platform: aht10
  #   address: 0x38
  #   variant: AHT20
  #   temperature:
  #     name: "Living Room Temperature"
  #   humidity:
  #     name: "Living Room Humidity"
  #   update_interval: 60s

  - platform: ltr_als_ps
    address: 0x29
    type: ALS
    update_interval: 60s

    # short variant of sensor definition:
    ambient_light: "Ambient light"
    

