sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

  - platform: veml7700
    address: 0x10
    update_interval: 60s

    # short variant of sensor definition:
    ambient_light: "Ambient light"
    # longer variant of sensor definition:
    actual_gain:
      name: "Actual gain"

