light:
  - platform: ${led_ring_platform}
    id: ${led_ring_id}
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

      - addressable_lambda:
          name: "Volume Display"
          update_interval: 50ms
          lambda: |-
            auto light_color = id(satellite1_led_ring).current_values;
            Color color(light_color.get_red() * 255, light_color.get_green() * 255,
                  light_color.get_blue() * 255);
            Color silenced_color(255, 0, 0);
            auto nb_leds_on = 12.0f * id(nabu_media_player).volume;
            for (int i = 0; i < 12; i++) {
              if (i < nb_leds_on) {
                it[(6+i)%12] = color;
              } else {
                it[(6+i)%12] = Color::BLACK;
              }
            }
            if (id(nabu_media_player).volume == 0.0f) {
              it[6] = silenced_color * 128;
            }

script:
  - id: control_leds
    then:
      - lambda: |
          if (id(init_in_progress)) {
            id(control_leds_init_state).execute();
          } else if (!id(wifi_id).is_connected() || !id(api_id).is_connected()){
            id(control_leds_no_ha_connection_state).execute();
          } else if (id(voice_assistant_phase) == ${voice_assist_listening_phase_id}) {
            id(control_led_voice_assist_listening_phase).execute();
          } else {
            id(control_leds_idle_state).execute();
          }

  - id: control_leds_idle_state
    then:
      - light.turn_off:
          id: ${led_ring_id}
  
  - id: control_leds_init_state
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 0%
          red: 0%
          green: 100%
          effect: "Fast Pulse"
  
  - id: control_leds_no_ha_connection_state
    then:
      - light.turn_off:
          id: ${led_ring_id}


  - id: control_leds_voice_assist_idle_phase
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 100%
          red: 100%
          green: 100%
          brightness: 20%
          effect: "none"


  # Script executed when the voice assistant is listening to a command: In this example: Turn the LED in blue with a slow pulse
  - id: control_led_voice_assist_listening_phase
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 100%
          red: 0%
          green: 0%
          effect: "Slow Pulse"


  # Script executed when the voice assistant is processing the command: In this example: Turn the LED in blue with a fast pulse      
  - id: control_led_voice_assist_thinking_phase
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 100%
          red: 0%
          green: 0%
          effect: "Fast Pulse"


  # Script executed when the voice assistant is replying to a command: In this example: Turn the LED in blue, solid (no pulse)       
  - id: control_led_voice_assist_replying_phase
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 100%
          red: 0%
          green: 0%
          brightness: 100%
          effect: "none"


  # Script executed when the voice assistant encounters an error: In this example: Turn the LED in red, solid (no pulse)       
  - id: control_led_voice_assist_error_phase
    then:
      - light.turn_on:
          id: ${led_ring_id}
          blue: 0%
          red: 100%
          green: 0%
          brightness: 100%
          effect: "none"


  # Script executed when the voice assistant is muted: In this example: Turn off the LED 
  - id: control_led_voice_assist_muted_phase
    then:
      - light.turn_off:
          id: ${led_ring_id}


  # Script executed when the voice assistant is not ready: In this example: Turn off the LED 
  - id: control_led_voice_assist_not_ready_phase
    then:
      - light.turn_off:
          id: ${led_ring_id}