external_components:
  - source:
      type: local
      path: /Users/siekmann/Privat/Projects/futureHome/nabu-voice-kit/esphome/components
    components: [ nabu, audio_dac, media_player ]

i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO02

media_player:
  - platform: nabu
    id: nabu_media_player
    name: Media Player
    internal: false
    sample_rate: 48000
    i2s_dout_pin: GPIO16
    bits_per_sample: 32bit
    i2s_mode: secondary
    i2s_audio_id: i2s_shared
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.85