text_sensor:
  - platform: version
    name: ${node_name}-firmware
    hide_timestamp: true

  - platform: template
    name: HW Revision
    entity_category: "diagnostic"
    update_interval: never
    lambda: |-
      return { "Core: Rev${core_revision}" };
     