name: Build-Satellite-Firmware

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.9"

jobs:

  build-firmware:
    uses: ./.github/workflows/build.yaml
    with:
      files: |
        config/satellite1.factory.yaml
        config/satellite1.ld2410.yaml
        config/satellite1.ld2450.yaml
      esphome-version: 2025.4.0
      release-summary: develop-branch
      release-url:
      release-version:
      combined-name: satellite1


  create_artifact_matrix:
    name: Create artifact matrix
    needs:
      - build-firmware
    outputs:
      matrix: ${{ steps.artifacts.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: files

      - run: tree

      - name: Get artifact names
        id: artifacts
        run: |
          artifacts=$(ls --format=single-column files)
          echo "artifacts<<EOF" >> $GITHUB_OUTPUT
          echo "$artifacts" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "matrix=$(ls files | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
