name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: config/satellite_mic_test.yaml #,esp8266.yml
      name: Satellite Mic test